# This file is used to define the REDIS service in the docker-compose file.

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - microservice-network

volumes:
  redis-data:
    driver: local

networks:
  microservice-network:
    driver: bridge